### ISSUE TITLE
Home icon en colmena lanza una excepción

### ISSUE THREAD

**Issue by RaquelSancha** [gpm0009/GESPRO_PracticaGestionTareas_1718#88]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.davidmiguel.gobees.mock, PID: 23858
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.davidmiguel.gobees.mock/com.davidmiguel.gobees.apiary.ApiaryActivity}: java.lang.IllegalArgumentException: No apiary id passed!
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
                      at android.app.ActivityThread.access$900(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
                      at android.os.Handler.dispatchMessage(Handler.java)
                      at android.os.Looper.loop(Looper.java)
                      at android.app.ActivityThread.main(ActivityThread.java)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                   Caused by: java.lang.IllegalArgumentException: No apiary id passed!
                      at com.davidmiguel.gobees.apiary.ApiaryActivity.onCreate(ApiaryActivity.java:60)
                      at android.app.Activity.performCreate(Activity.java)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
                      at android.app.ActivityThread.access$900(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
                      at android.os.Handler.dispatchMessage(Handler.java) 
                      at android.os.Looper.loop(Looper.java) 
                      at android.app.ActivityThread.main(ActivityThread.java) 
                      at java.lang.reflect.Method.invoke(Native Method)

**Comment by gpm0009** [comment]
creo que esa estimación.....se queda corta, considero que nos llevara mas

**Comment by jgo0038** [comment]
Deberías cambiarlo a 5 el tiempo estimado, parece complicado.

**Comment by ZoeCalvo** [comment]
Estoy de acuerdo, tu estimación es bastante corta.
